name: wf-push

on:
  push
jobs:
  push1:
    name: flag_evaulation
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "##[set-output name=a;]$(echo "a")"
          echo "##[set-output name=b;]$(echo "b")"
        id: esito
      - run: |
          var = ${{steps.esito.outputs.a}}
          echo $var
          echo ${{steps.esito.outputs.a}} , ${{steps.esito.outputs.b}}
  pat-vida:
    name: pat vida
    runs-on: ubuntu-latest
    needs: [push1]
    steps:
      - run: echo ${{steps.esito.outputs.a}}

