name: wf-push

on:
  push
jobs:
  push1:
    #if: ${{default_input_flag == "true"}}
    env:
      input_flag: ${{secrets.DEFAULT_INPUT_FLAG}}
    name: flag_true
    runs-on: ubuntu-latest
    steps:
      - run: echo "true"
        if: env.input_flag == 'true'
      - run: echo "true"
        if: env.input_flag != 'true'
      - run: echo "false"
  
