name: wf-push
env:
  INPUT_FLAG: ${{ secrets.DEFAULT_INPUT_FLAG }}

on:
  push
jobs:
  push1:
    #if: ${{default_input_flag == "true"}}
    name: flag_true
    runs-on: ubuntu-latest
    steps:
      - run: env
  push2:
    #if: ${{ default_input_flag == "false" }}
    name: flag_false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $INPUT_FLAG
          var=$INPUT_FLAG
          if [ $var == "" ]; then echo "false"
          elif [ $var == "false" ]; then echo "false"
          elif [ $var == "true"  ]; then echo "true"
          else 
          echo "stop"
          fi
          
