name: wf-push

on:
  push
jobs:
  push1:
    #if: ${{default_input_flag == "true"}}
    env:
      input_flag: ${{secrets.DEFAULT_INPUT_FLAG}}
    name: flag_evaulation
    runs-on: ubuntu-latest
    steps:

      - run: |
          if [ ${{env.input_flag}} == "true" ]; then
          echo "::set-output name=flag::t"
          else
          echo "::set-output name=flag::f"
        id: esito
      - run: |
          echo ${{steps.esito.outputs.flag}}
  
