name: wf-push

on:
  push
jobs:
  push1:
    if: secrets.DEFAULT_INPUT_FLAG == "true"
    name: flag_true
    runs-on: ubuntu-latest
    steps:
      - run: env
  push2:
    if: secrets.DEFAULT_INPUT_FLAG == "false"
    name: flag_false
    runs-on: ubuntu-latest
    steps:
      - run: env
