name: tagging

on:
  pull_request:
    types: closed
jobs:
  pr:
    name: pull request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - run: env
