name: pr

on:
  pull_request:
    types: closed
jobs:
  pr:
    name: pull request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - run: env
    
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=new-tag;]$(declare -a list=$(git tag); python3 generate-tag.py ${list[*]})"
        id: extract_tag
        
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout master
          git tag -a ${{steps.extract_tag.outputs.new-tag}} HEAD -m "added tag"
          git push --tags

