name: push-hotfix

on:
  pull_request:
    types: closed

jobs:
  
  update-develop-branch:
    name: Update Develop Branch
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        && (contains(github.head_ref, 'hotfix') || contains(github.head_ref, 'releases')) 
  
    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout develop
          git branch -a
    
